version: '3.8'

services:

  postgres:
    image: postgres:latest
    container_name: postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=cornel
      - POSTGRES_PASSWORD=sefusefu
      - POSTGRES_DB=postgresql_database
    networks:
      - pn

  springboot:
    build: .
    container_name: springboot
    links:
      - postgres
    ports:
      - 8080:8080
    networks:
      - pn

networks:
  pn:
    name: pn
    driver: bridge