services:

  database_service:
    image: postgres:latest
    container_name: database
    environment:
      - POSTGRES_USER=cornel
      - POSTGRES_PASSWORD=sefusefu
      - POSTGRES_DB=my_database
    network_mode: service:application_service

  application_service:
    image: my-docker-image
    container_name: application
    ports:
      - "8080:8080"
    network_mode: bridge
