spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        search:
          default:
            indexmanager: elasticsearch
            elasticsearch:
              host: localhost:9200
              index_schema_management_strategy: drop-and-create
              required_index_status: yellow
  hibernate:
    ddl-auto: create-drop
  show-sql: true
  open-in-view: false