spring:
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        ddl-auto: create-drop
        format_sql: true
        search:
          default:
#            indexBase: /app/microservices/test/parent
#            indexmanager: elasticsearch
            elasticsearch:
#              host: localhost:9200
#              index_schema_management_strategy: CREATE
              version: 7.5.1
#              required_index_status: yellow
          automatic_indexing:
#            strategy: none
            synchronization:
              strategy: sync